export interface TimezoneOption {
  value: string;
  label: string;
  offset: number;
}

export const ALL_TIMEZONES: TimezoneOption[] = [
  // UTC-12
  { value: "Etc/GMT+12", label: "International Date Line West (UTC-12)", offset: -12 },
  { value: "Pacific/Pago_Pago", label: "Pago Pago, American Samoa (UTC-11)", offset: -11 },
  { value: "Pacific/Midway", label: "Midway Island (UTC-11)", offset: -11 },
  { value: "Pacific/Honolulu", label: "Honolulu, Hawaii (HST, UTC-10)", offset: -10 },
  { value: "Pacific/Rarotonga", label: "Rarotonga, Cook Islands (UTC-10)", offset: -10 },
  { value: "Pacific/Tahiti", label: "Tahiti, French Polynesia (UTC-10)", offset: -10 },
  { value: "Pacific/Marquesas", label: "Marquesas Islands (UTC-9:30)", offset: -9.5 },
  { value: "America/Anchorage", label: "Anchorage, Alaska (AKST, UTC-9)", offset: -9 },
  { value: "America/Juneau", label: "Juneau, Alaska (AKST, UTC-9)", offset: -9 },
  { value: "Pacific/Gambier", label: "Gambier Islands (UTC-9)", offset: -9 },
  { value: "America/Los_Angeles", label: "Los Angeles, California (PST, UTC-8)", offset: -8 },
  { value: "America/Vancouver", label: "Vancouver, Canada (PST, UTC-8)", offset: -8 },
  { value: "America/Seattle", label: "Seattle, Washington (PST, UTC-8)", offset: -8 },
  { value: "America/Tijuana", label: "Tijuana, Mexico (PST, UTC-8)", offset: -8 },
  { value: "America/Las_Vegas", label: "Las Vegas, Nevada (PST, UTC-8)", offset: -8 },
  { value: "Pacific/Pitcairn", label: "Pitcairn Islands (UTC-8)", offset: -8 },
  { value: "America/Denver", label: "Denver, Colorado (MST, UTC-7)", offset: -7 },
  { value: "America/Phoenix", label: "Phoenix, Arizona (MST, UTC-7)", offset: -7 },
  { value: "America/Calgary", label: "Calgary, Canada (MST, UTC-7)", offset: -7 },
  { value: "America/Edmonton", label: "Edmonton, Canada (MST, UTC-7)", offset: -7 },
  { value: "America/Mazatlan", label: "Mazatlan, Mexico (MST, UTC-7)", offset: -7 },
  { value: "America/Chihuahua", label: "Chihuahua, Mexico (MST, UTC-7)", offset: -7 },
  { value: "America/Chicago", label: "Chicago, Illinois (CST, UTC-6)", offset: -6 },
  { value: "America/Mexico_City", label: "Mexico City, Mexico (CST, UTC-6)", offset: -6 },
  { value: "America/Winnipeg", label: "Winnipeg, Canada (CST, UTC-6)", offset: -6 },
  { value: "America/Guatemala", label: "Guatemala City, Guatemala (UTC-6)", offset: -6 },
  { value: "America/El_Salvador", label: "San Salvador, El Salvador (UTC-6)", offset: -6 },
  { value: "America/Costa_Rica", label: "San Jose, Costa Rica (UTC-6)", offset: -6 },
  { value: "America/Tegucigalpa", label: "Tegucigalpa, Honduras (UTC-6)", offset: -6 },
  { value: "America/Managua", label: "Managua, Nicaragua (UTC-6)", offset: -6 },
  { value: "America/New_York", label: "New York, USA (EST, UTC-5)", offset: -5 },
  { value: "America/Toronto", label: "Toronto, Canada (EST, UTC-5)", offset: -5 },
  { value: "America/Miami", label: "Miami, Florida (EST, UTC-5)", offset: -5 },
  { value: "America/Boston", label: "Boston, Massachusetts (EST, UTC-5)", offset: -5 },
  { value: "America/Detroit", label: "Detroit, Michigan (EST, UTC-5)", offset: -5 },
  { value: "America/Atlanta", label: "Atlanta, Georgia (EST, UTC-5)", offset: -5 },
  { value: "America/Lima", label: "Lima, Peru (UTC-5)", offset: -5 },
  { value: "America/Bogota", label: "Bogota, Colombia (UTC-5)", offset: -5 },
  { value: "America/Panama", label: "Panama City, Panama (UTC-5)", offset: -5 },
  { value: "America/Havana", label: "Havana, Cuba (UTC-5)", offset: -5 },
  { value: "America/Jamaica", label: "Kingston, Jamaica (UTC-5)", offset: -5 },
  { value: "America/Cancun", label: "Cancun, Mexico (EST, UTC-5)", offset: -5 },
  { value: "America/Guayaquil", label: "Guayaquil, Ecuador (UTC-5)", offset: -5 },
  { value: "America/Halifax", label: "Halifax, Canada (AST, UTC-4)", offset: -4 },
  { value: "America/Santiago", label: "Santiago, Chile (UTC-4)", offset: -4 },
  { value: "America/Caracas", label: "Caracas, Venezuela (UTC-4)", offset: -4 },
  { value: "America/La_Paz", label: "La Paz, Bolivia (UTC-4)", offset: -4 },
  { value: "America/Manaus", label: "Manaus, Brazil (AMT, UTC-4)", offset: -4 },
  { value: "America/Puerto_Rico", label: "San Juan, Puerto Rico (AST, UTC-4)", offset: -4 },
  { value: "America/Barbados", label: "Bridgetown, Barbados (AST, UTC-4)", offset: -4 },
  { value: "America/Guyana", label: "Georgetown, Guyana (UTC-4)", offset: -4 },
  { value: "America/St_Johns", label: "St. Johns, Newfoundland (NST, UTC-3:30)", offset: -3.5 },
  { value: "America/Sao_Paulo", label: "Sao Paulo, Brazil (BRT, UTC-3)", offset: -3 },
  { value: "America/Argentina/Buenos_Aires", label: "Buenos Aires, Argentina (UTC-3)", offset: -3 },
  { value: "America/Montevideo", label: "Montevideo, Uruguay (UTC-3)", offset: -3 },
  { value: "America/Asuncion", label: "Asuncion, Paraguay (UTC-3)", offset: -3 },
  { value: "America/Fortaleza", label: "Fortaleza, Brazil (UTC-3)", offset: -3 },
  { value: "Atlantic/Stanley", label: "Stanley, Falkland Islands (UTC-3)", offset: -3 },
  { value: "America/Noronha", label: "Fernando de Noronha, Brazil (UTC-2)", offset: -2 },
  { value: "Atlantic/South_Georgia", label: "South Georgia Island (UTC-2)", offset: -2 },
  { value: "Atlantic/Azores", label: "Azores, Portugal (UTC-1)", offset: -1 },
  { value: "Atlantic/Cape_Verde", label: "Praia, Cape Verde (UTC-1)", offset: -1 },
  { value: "Europe/London", label: "London, UK (GMT, UTC+0)", offset: 0 },
  { value: "Europe/Dublin", label: "Dublin, Ireland (GMT, UTC+0)", offset: 0 },
  { value: "Europe/Lisbon", label: "Lisbon, Portugal (WET, UTC+0)", offset: 0 },
  { value: "Africa/Casablanca", label: "Casablanca, Morocco (UTC+0)", offset: 0 },
  { value: "Africa/Dakar", label: "Dakar, Senegal (UTC+0)", offset: 0 },
  { value: "Africa/Accra", label: "Accra, Ghana (UTC+0)", offset: 0 },
  { value: "Atlantic/Reykjavik", label: "Reykjavik, Iceland (UTC+0)", offset: 0 },
  { value: "Europe/Paris", label: "Paris, France (CET, UTC+1)", offset: 1 },
  { value: "Europe/Berlin", label: "Berlin, Germany (CET, UTC+1)", offset: 1 },
  { value: "Europe/Amsterdam", label: "Amsterdam, Netherlands (CET, UTC+1)", offset: 1 },
  { value: "Europe/Brussels", label: "Brussels, Belgium (CET, UTC+1)", offset: 1 },
  { value: "Europe/Madrid", label: "Madrid, Spain (CET, UTC+1)", offset: 1 },
  { value: "Europe/Rome", label: "Rome, Italy (CET, UTC+1)", offset: 1 },
  { value: "Europe/Vienna", label: "Vienna, Austria (CET, UTC+1)", offset: 1 },
  { value: "Europe/Zurich", label: "Zurich, Switzerland (CET, UTC+1)", offset: 1 },
  { value: "Europe/Stockholm", label: "Stockholm, Sweden (CET, UTC+1)", offset: 1 },
  { value: "Europe/Oslo", label: "Oslo, Norway (CET, UTC+1)", offset: 1 },
  { value: "Europe/Copenhagen", label: "Copenhagen, Denmark (CET, UTC+1)", offset: 1 },
  { value: "Europe/Warsaw", label: "Warsaw, Poland (CET, UTC+1)", offset: 1 },
  { value: "Europe/Prague", label: "Prague, Czech Republic (CET, UTC+1)", offset: 1 },
  { value: "Europe/Budapest", label: "Budapest, Hungary (CET, UTC+1)", offset: 1 },
  { value: "Africa/Lagos", label: "Lagos, Nigeria (WAT, UTC+1)", offset: 1 },
  { value: "Africa/Tunis", label: "Tunis, Tunisia (UTC+1)", offset: 1 },
  { value: "Africa/Algiers", label: "Algiers, Algeria (UTC+1)", offset: 1 },
  { value: "Europe/Helsinki", label: "Helsinki, Finland (EET, UTC+2)", offset: 2 },
  { value: "Europe/Tallinn", label: "Tallinn, Estonia (EET, UTC+2)", offset: 2 },
  { value: "Europe/Riga", label: "Riga, Latvia (EET, UTC+2)", offset: 2 },
  { value: "Europe/Bucharest", label: "Bucharest, Romania (EET, UTC+2)", offset: 2 },
  { value: "Europe/Athens", label: "Athens, Greece (EET, UTC+2)", offset: 2 },
  { value: "Europe/Kiev", label: "Kyiv, Ukraine (EET, UTC+2)", offset: 2 },
  { value: "Asia/Jerusalem", label: "Jerusalem, Israel (IST, UTC+2)", offset: 2 },
  { value: "Asia/Beirut", label: "Beirut, Lebanon (EET, UTC+2)", offset: 2 },
  { value: "Asia/Amman", label: "Amman, Jordan (EET, UTC+2)", offset: 2 },
  { value: "Africa/Cairo", label: "Cairo, Egypt (EET, UTC+2)", offset: 2 },
  { value: "Africa/Johannesburg", label: "Johannesburg, South Africa (SAST, UTC+2)", offset: 2 },
  { value: "Africa/Harare", label: "Harare, Zimbabwe (SAST, UTC+2)", offset: 2 },
  { value: "Europe/Moscow", label: "Moscow, Russia (MSK, UTC+3)", offset: 3 },
  { value: "Europe/Istanbul", label: "Istanbul, Turkey (TRT, UTC+3)", offset: 3 },
  { value: "Asia/Riyadh", label: "Riyadh, Saudi Arabia (AST, UTC+3)", offset: 3 },
  { value: "Asia/Kuwait", label: "Kuwait City, Kuwait (AST, UTC+3)", offset: 3 },
  { value: "Asia/Qatar", label: "Doha, Qatar (AST, UTC+3)", offset: 3 },
  { value: "Asia/Baghdad", label: "Baghdad, Iraq (AST, UTC+3)", offset: 3 },
  { value: "Africa/Nairobi", label: "Nairobi, Kenya (EAT, UTC+3)", offset: 3 },
  { value: "Africa/Addis_Ababa", label: "Addis Ababa, Ethiopia (EAT, UTC+3)", offset: 3 },
  { value: "Africa/Dar_es_Salaam", label: "Dar es Salaam, Tanzania (EAT, UTC+3)", offset: 3 },
  { value: "Asia/Tehran", label: "Tehran, Iran (IRST, UTC+3:30)", offset: 3.5 },
  { value: "Asia/Dubai", label: "Dubai, UAE (GST, UTC+4)", offset: 4 },
  { value: "Asia/Abu_Dhabi", label: "Abu Dhabi, UAE (GST, UTC+4)", offset: 4 },
  { value: "Asia/Muscat", label: "Muscat, Oman (GST, UTC+4)", offset: 4 },
  { value: "Asia/Baku", label: "Baku, Azerbaijan (AZT, UTC+4)", offset: 4 },
  { value: "Asia/Tbilisi", label: "Tbilisi, Georgia (GET, UTC+4)", offset: 4 },
  { value: "Asia/Yerevan", label: "Yerevan, Armenia (AMT, UTC+4)", offset: 4 },
  { value: "Indian/Mauritius", label: "Port Louis, Mauritius (MUT, UTC+4)", offset: 4 },
  { value: "Asia/Kabul", label: "Kabul, Afghanistan (AFT, UTC+4:30)", offset: 4.5 },
  { value: "Asia/Karachi", label: "Karachi, Pakistan (PKT, UTC+5)", offset: 5 },
  { value: "Asia/Tashkent", label: "Tashkent, Uzbekistan (UZT, UTC+5)", offset: 5 },
  { value: "Indian/Maldives", label: "Male, Maldives (MVT, UTC+5)", offset: 5 },
  { value: "Asia/Kolkata", label: "Mumbai / Delhi / Kolkata, India (IST, UTC+5:30)", offset: 5.5 },
  { value: "Asia/Colombo", label: "Colombo, Sri Lanka (SLST, UTC+5:30)", offset: 5.5 },
  { value: "Asia/Kathmandu", label: "Kathmandu, Nepal (NPT, UTC+5:45)", offset: 5.75 },
  { value: "Asia/Dhaka", label: "Dhaka, Bangladesh (BST, UTC+6)", offset: 6 },
  { value: "Asia/Almaty", label: "Almaty, Kazakhstan (ALMT, UTC+6)", offset: 6 },
  { value: "Asia/Thimphu", label: "Thimphu, Bhutan (BTT, UTC+6)", offset: 6 },
  { value: "Asia/Yangon", label: "Yangon, Myanmar (MMT, UTC+6:30)", offset: 6.5 },
  { value: "Asia/Bangkok", label: "Bangkok, Thailand (ICT, UTC+7)", offset: 7 },
  { value: "Asia/Jakarta", label: "Jakarta, Indonesia (WIB, UTC+7)", offset: 7 },
  { value: "Asia/Ho_Chi_Minh", label: "Ho Chi Minh City, Vietnam (ICT, UTC+7)", offset: 7 },
  { value: "Asia/Hanoi", label: "Hanoi, Vietnam (ICT, UTC+7)", offset: 7 },
  { value: "Asia/Phnom_Penh", label: "Phnom Penh, Cambodia (ICT, UTC+7)", offset: 7 },
  { value: "Asia/Vientiane", label: "Vientiane, Laos (ICT, UTC+7)", offset: 7 },
  { value: "Asia/Novosibirsk", label: "Novosibirsk, Russia (NOVT, UTC+7)", offset: 7 },
  { value: "Asia/Hong_Kong", label: "Hong Kong (HKT, UTC+8)", offset: 8 },
  { value: "Asia/Shanghai", label: "Shanghai / Beijing, China (CST, UTC+8)", offset: 8 },
  { value: "Asia/Chongqing", label: "Chongqing, China (CST, UTC+8)", offset: 8 },
  { value: "Asia/Singapore", label: "Singapore (SGT, UTC+8)", offset: 8 },
  { value: "Asia/Kuala_Lumpur", label: "Kuala Lumpur, Malaysia (MYT, UTC+8)", offset: 8 },
  { value: "Asia/Taipei", label: "Taipei, Taiwan (CST, UTC+8)", offset: 8 },
  { value: "Asia/Manila", label: "Manila, Philippines (PHT, UTC+8)", offset: 8 },
  { value: "Asia/Macau", label: "Macau (CST, UTC+8)", offset: 8 },
  { value: "Asia/Ulaanbaatar", label: "Ulaanbaatar, Mongolia (ULAT, UTC+8)", offset: 8 },
  { value: "Australia/Perth", label: "Perth, Australia (AWST, UTC+8)", offset: 8 },
  { value: "Asia/Tokyo", label: "Tokyo, Japan (JST, UTC+9)", offset: 9 },
  { value: "Asia/Osaka", label: "Osaka, Japan (JST, UTC+9)", offset: 9 },
  { value: "Asia/Seoul", label: "Seoul, South Korea (KST, UTC+9)", offset: 9 },
  { value: "Asia/Yakutsk", label: "Yakutsk, Russia (YAKT, UTC+9)", offset: 9 },
  { value: "Australia/Darwin", label: "Darwin, Australia (ACST, UTC+9:30)", offset: 9.5 },
  { value: "Australia/Adelaide", label: "Adelaide, Australia (ACST, UTC+9:30)", offset: 9.5 },
  { value: "Australia/Sydney", label: "Sydney, Australia (AEST, UTC+10)", offset: 10 },
  { value: "Australia/Melbourne", label: "Melbourne, Australia (AEST, UTC+10)", offset: 10 },
  { value: "Australia/Brisbane", label: "Brisbane, Australia (AEST, UTC+10)", offset: 10 },
  { value: "Pacific/Port_Moresby", label: "Port Moresby, Papua New Guinea (PGT, UTC+10)", offset: 10 },
  { value: "Pacific/Guam", label: "Hagatna, Guam (ChST, UTC+10)", offset: 10 },
  { value: "Asia/Vladivostok", label: "Vladivostok, Russia (VLAT, UTC+10)", offset: 10 },
  { value: "Pacific/Guadalcanal", label: "Honiara, Solomon Islands (SBT, UTC+11)", offset: 11 },
  { value: "Pacific/Noumea", label: "Noumea, New Caledonia (NCT, UTC+11)", offset: 11 },
  { value: "Pacific/Auckland", label: "Auckland, New Zealand (NZST, UTC+12)", offset: 12 },
  { value: "Pacific/Fiji", label: "Suva, Fiji (FJT, UTC+12)", offset: 12 },
  { value: "Pacific/Chatham", label: "Chatham Islands, NZ (CHAST, UTC+12:45)", offset: 12.75 },
  { value: "Pacific/Tongatapu", label: "Nukualofa, Tonga (TOT, UTC+13)", offset: 13 },
  { value: "Pacific/Apia", label: "Apia, Samoa (WST, UTC+13)", offset: 13 },
  { value: "Pacific/Kiritimati", label: "Christmas Island, Kiribati (LINT, UTC+14)", offset: 14 },
];

export const COMMON_TIMEZONES = ALL_TIMEZONES;
export type TimezoneValue = string;
